# Generated by Django 3.2.9 on 2021-11-22 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('sim_id', models.PositiveIntegerField(default=0)),
                ('phone', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('pin', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('a', 'active'), ('n', 'nonactive'), ('l', 'locked')], max_length=1, null=True)),
                ('is_used_by_modem', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('imei', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('sim_phone', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.sim')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_send', models.DateTimeField(auto_now=True)),
                ('date_received', models.DateTimeField(auto_now=True)),
                ('receiver_phone', models.PositiveBigIntegerField()),
                ('text', models.TextField()),
                ('unicode', models.CharField(default='U+000A', max_length=64)),
                ('status', models.CharField(choices=[('r', 'received'), ('p', 'pending')], default='p', max_length=1, null=True)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sender_phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.sim')),
            ],
        ),
    ]
